services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_INTERNAL_PORT}
    depends_on:
      - postgres
      - node
    environment:
      NODE_PORT: ${NODE_PORT}
      PORT: ${NGINX_INTERNAL_PORT}

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data/

  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - ./backend/:/app/
    depends_on:
      - postgres
    entrypoint: ./start.sh
    environment:
      PORT: ${NODE_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
