services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx.Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data/
  backend:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 80:${NODE_PORT}
    volumes:
      - ./backend/:/app/
    depends_on:
      - postgres
    entrypoint: ./start.sh
    environment:
      PORT: ${NODE_PORT}
